package tallerN1_compiladores;

public enum Token {
	ELSE, IF, RETURN, VOID, WHILE, DO, INT, ASSIGN, SUMA, MULT, RESTA, DIV, MENOR,
	MENIGUAL, MAYOR, MAYIGUAL, IGUALIGUAL, DISTINTO, PUNTOCOMA, COMA, PARENTHLEFT,
	PARENTHRIGHT, BRACKETLEFT, BRACKETRIGHT,BRACELEFT,BRACERIGHT, 
	COMENTLEFT, COMENTRIGHT, DOUBLESLASH, ID, NUM, ERROR, COMENTARIO
	
}
